### ISSUE TITLE
A visitor can see the following partners

### ISSUE THREAD

**Issue by mfekadu** [colorcoded/colorcoded.github.io#11]
Google, Microsoft, iFixit, CSSE (logo attached)

and the logos should be much less than 300 px (current size on commit 1dcdac479f7353adb343114a9a38457fa60b74ef)

<img width="311" alt="csse2" src="https://user-images.githubusercontent.com/11131250/55510908-2d3fc780-5614-11e9-878a-2fe4e61152bc.png">

**Comment by jpcastil** [comment]
Done
